---
name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Python | Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Pre-Commit | Run
      uses: pre-commit/action@v3.0.0
